#Combing Through the Haystack
#SUBS

#f_in = open('subs.txt','rU')
#seqs = f_in.readlines()

def find(super, sub):
    import re
    go = 1
    L = []
    count = 0
    while go == 1:
        match = re.search(sub, super)
        if match:
            super = super[match.start(0)+1:]
            count += match.start(0)+1
            L.append(count)
            continue
        else:
            go = 0
            break
    return L

seq = 'CTGAGGGCAGGAAAAGGGCAGCCATAGGGCAGCCAGGGCAGCACAAGGGCAGAGGGCAGTCAGGGCAGATAGGGCAGCAGGGCAGCTTAGGGCAGTAGGGCAGGGAGGGCAGAGGGCAGCATAGGGCAGCGCGAGGGCAGAAGCGACCAGGGCAGGGGATAGGGCAGTTTCCCTTCGCTAGGGCAGGGGCAATGTTCGCTCAGGGCAGAGGGCAGAGGGCAGGGTTCAGGGCAGCAGGGCAGGAGGGCAGAGGGCAGGAGGGCAGTAATACAGGGCAGGGGAAAGGGCAGAAGGGCAGAAGGGCAGACTAGGCTATGCCGTCCGTTGGCTAGGGCAGAGAGGGCAGAGGGCAGTACCCACAGGGCAGCAGGGCAGAGGGCAGAATCAGGGCAGTGAGGGCAGTGACAAAAATTAGGGCAGAAGGGCAGAGGGCAGGGTTGCTGACAGAGGGCAGCGAGGGCAGACAGGGCAGATAGGGCAGCGCAGGGCAGGCGAGGGCAGAGGGCAGTCCCGAGGGCAGAGGGCAGACGGTAGGGCAGGAGAGGGCAGGCTAGGGCAGAGGGCAGTTCAGGGCAGGAGGGCAGACGCGACTCAGGGCAGCAAGGGCAGCCCTAGGGCAGCATACAAGGGCAGGCGAGGGCAGAGGGCAGCCTTAAGGGCAGGAAGGGCAGATGGATCGAGGGCAGTACCGATAAAAGGGCAGAGGGCAGTTAGGGCAGAACAGGGCAGAGGCTAGGGCAGCCGCTCGTCCAGGGCAGAAGGGCAGTAGGGCAGTAGGGCAGAGAGGGCAGAGGGCAGCAGTGAGGGCAGCAGGGCAGGAGCAGGGCAGGCAAGGGCAGAGCCAGGGCAGCGACACATAGGGCAGTGAGGGCAGAAGGCCTTAGGGCAGGTTGAGGGCAGAGGGCAGTCTGCGAGGGCAGAGGGCAGGAGGGCAGTCCTTTCGT'
sub = 'AGGGCAGAG'

print(find(seq,sub))